# Remote state in S3 with DynamoDB locking.
#
# Backend blocks cannot interpolate variables, so the concrete values come from
# `terraform init -backend-config=backend.hcl`. That file is generated by
# scripts/bootstrap.sh from the bootstrap stack's outputs and is gitignored --
# it embeds the AWS account ID.
terraform {
  backend "s3" {}
}
